// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DashboardChartController from "./dashboard_chart_controller"
application.register("dashboard-chart", DashboardChartController)

import JournalCalculatorController from "./journal_calculator_controller"
application.register("journal-calculator", JournalCalculatorController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)
